### ISSUE TITLE
Compilation error on Node v6

### ISSUE THREAD

**Issue by katyo** [Venemo/node-lmdb#123]
There is an issue with compiling:

```
../src/cursor.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE CursorWrap::getCommon(Nan::NAN_METHOD_ARGS_TYPE, MDB_cursor_op, void (* (*)(CursorWrap*, Nan::NAN_METHOD_ARGS_TYPE, MDB_val&, bool&))(MDB_val&), void (*)(CursorWrap*, Nan::NAN_METHOD_ARGS_TYPE, MDB_val&), void (*)(CursorWrap*, Nan::NAN_METHOD_ARGS_TYPE, MDB_val&), v8::Local<v8::Value> (*)(MDB_val&)
’:
../src/cursor.cpp:208:43: error: passing ‘const v8::Local<v8::Value>’ as ‘this’ argument discards qualifiers [-fpermissive]
                 callbackFunc.As<Function>()->Call(Nan::Undefined(), argc, argv);
                                           ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/cursor.cpp:24:
/home/kayo/.node-gyp/6.12.3/include/node/v8.h:296:41: note:   in call to ‘v8::Local<S> v8::Local<T>::As() [with S = v8::Function; T = v8::Value]’
   template <class S> V8_INLINE Local<S> As() {
                                         ^~
```

node v6.12.3
npm  v3.10.10
gcc v6.3.0

**Comment by Venemo** [comment]
This is caused by: https://github.com/Venemo/node-lmdb/commit/d0ed6904c4665b6e964fde3d22e193e4f51c5478 --- need to check the Nan docs for how to do this correctly.

**Comment by Venemo** [comment]
@katyo I fixed this in latest master, now can compile on node `v6.11.4`. Can you verify that it works for you now? Thanks.
