### ISSUE TITLE
Build error on old node v0.10

### ISSUE THREAD

**Issue by mux** [Venemo/node-lmdb#87]
I cannot seem to build node-lmdb 0.4.3 properly. It looks like the NewInstance method the code is trying to use isn't defined somehow, see output below. Any help would be greatly appreciated.

Thanks!

```> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/node-lmdb/src/env.o
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v11-linux-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v11-linux-x64.tar.gz
[sqlite3] Success: "/home/mhenrion/adserver-regressions/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node" is installed via remote
../src/env.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE EnvWrap::beginTxn(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/env.cpp:170:97: error: no matching function for call to ‘v8::Function::NewInstance(v8::Local<v8::Context>, const int&, v8::Local<v8::Value> [2])’
     Local<Object> instance = Nan::New(txnCtor)->NewInstance(Nan::GetCurrentContext(), argc, argv).ToLocalChecked();
                                                                                                 ^
../src/env.cpp:170:97: note: candidates are:
In file included from ../src/node-lmdb.h:27:0,
                 from ../src/env.cpp:24:
/usr/include/nodejs/deps/v8/include/v8.h:1772:26: note: v8::Local<v8::Object> v8::Function::NewInstance() const
   V8EXPORT Local<Object> NewInstance() const;
                          ^
/usr/include/nodejs/deps/v8/include/v8.h:1772:26: note:   candidate expects 0 arguments, 3 provided
/usr/include/nodejs/deps/v8/include/v8.h:1773:26: note: v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Handle<v8::Value>*) const
   V8EXPORT Local<Object> NewInstance(int argc, Handle<Value> argv[]) const;
                          ^
/usr/include/nodejs/deps/v8/include/v8.h:1773:26: note:   candidate expects 2 arguments, 3 provided
../src/env.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE EnvWrap::openDbi(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/env.cpp:181:5: error: ‘MaybeLocal’ was not declared in this scope
     MaybeLocal<Object> maybeInstance = Nan::New(dbiCtor)->NewInstance(Nan::GetCurrentContext(), argc, argv);
     ^
../src/env.cpp:181:5: note: suggested alternative:
In file included from ../node_modules/nan/nan.h:192:0,
                 from ../src/node-lmdb.h:30,
                 from ../src/env.cpp:24:
../node_modules/nan/nan_maybe_pre_43_inl.h:13:7: note:   ‘Nan::MaybeLocal’
 class MaybeLocal {
       ^
../src/env.cpp:181:22: error: expected primary-expression before ‘>’ token
     MaybeLocal<Object> maybeInstance = Nan::New(dbiCtor)->NewInstance(Nan::GetCurrentContext(), argc, argv);
                      ^
../src/env.cpp:181:24: error: ‘maybeInstance’ was not declared in this scope
     MaybeLocal<Object> maybeInstance = Nan::New(dbiCtor)->NewInstance(Nan::GetCurrentContext(), argc, argv);
                        ^
../src/env.cpp:181:107: error: no matching function for call to ‘v8::Function::NewInstance(v8::Local<v8::Context>, const unsigned int&, v8::Local<v8::Value> [2])’
     MaybeLocal<Object> maybeInstance = Nan::New(dbiCtor)->NewInstance(Nan::GetCurrentContext(), argc, argv);
                                                                                                           ^
../src/env.cpp:181:107: note: candidates are:
In file included from ../src/node-lmdb.h:27:0,
                 from ../src/env.cpp:24:
/usr/include/nodejs/deps/v8/include/v8.h:1772:26: note: v8::Local<v8::Object> v8::Function::NewInstance() const
   V8EXPORT Local<Object> NewInstance() const;
                          ^
/usr/include/nodejs/deps/v8/include/v8.h:1772:26: note:   candidate expects 0 arguments, 3 provided
/usr/include/nodejs/deps/v8/include/v8.h:1773:26: note: v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Handle<v8::Value>*) const
   V8EXPORT Local<Object> NewInstance(int argc, Handle<Value> argv[]) const;
                          ^
/usr/include/nodejs/deps/v8/include/v8.h:1773:26: note:   candidate expects 2 arguments, 3 provided
make: *** [Release/obj.target/node-lmdb/src/env.o] Error 1
make: Leaving directory `/home/mhenrion/adserver-regressions/node_modules/node-lmdb/build'
```

**Comment by Venemo** [comment]
Thanks for reporting this! Could you please give me some more details? Such as:

* What operating system are you running? (And which version?)
* Which node version do you use?
* Did you run `npm install` before attempting to build the module?
* Did you make sure that you have the latest revision before attempting to build the module?

**Comment by mux** [comment]
My apologies, I should have given you this information to begin with - I was hoping this would be an obvious issue due to some functions being deprecated or something.

Anyways:

- System is Ubuntu:

```$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty```

- v8 version is:

```[mhenrion@318.bm-mhenrion.user.nym2 ~/adserver-regressions]
$ dpkg -l | grep v8
ii  libv8-3.14-dev                      3.14.5.8-5ubuntu2                   amd64        V8 JavaScript engine - development files for 3.14 branch
ii  libv8-3.14.5                        3.14.5.8-5ubuntu2                   amd64        V8 JavaScript engine - runtime library```

- Yes, I actually get that error when running `npm install node-lmdb`

- I believe so, it is node-lmdb 0.4.3 as you can see from the first few output lines of npm install:

```$ npm install node-lmdb
npm WARN package.json adserver-regressions@0.2.13 No repository field.
npm http GET https://npm.corp.appnexus.com/node-lmdb
npm http 304 https://npm.corp.appnexus.com/node-lmdb
npm http GET https://npm.corp.appnexus.com/bindings
npm http GET https://npm.corp.appnexus.com/nan
npm http 304 https://npm.corp.appnexus.com/bindings
npm http 304 https://npm.corp.appnexus.com/nan

> node-lmdb@0.4.3 install /home/mhenrion/adserver-regressions/node_modules/node-lmdb
> node-gyp rebuild```

Thanks!

**Comment by Venemo** [comment]
Can you also give me your node version? Just run `node --version`.

**Comment by mux** [comment]
Oops, sorry, here it is:

```$ node --version
v0.10.25
```

**Comment by Venemo** [comment]
Could you try with a newer node version? `v0.10.25` is very old.

**Comment by mux** [comment]
I'm currently negotiating this with admins here to get at a newer version, I'll let you know!

**Comment by mux** [comment]
I can confirm that node-lmdb builds just fine using node 4.x. Unfortunately the upgrade isn't easy as we depend on other packages that don't work for node 4. I'm still trying to work around these issues, but if you happen to have a workaround to allow building with 0.10.x that would be great.

**Comment by braydonf** [comment]
Maintenance period has ended for v0.10, as from: https://github.com/nodejs/LTS

**Comment by Venemo** [comment]
I don't know if we can support node 0.10. The compilation error comes from a library we depend on (called nan), so if they don't support node 0.10 then there isn't much we can do about it.

@mux If you are looking for a woraround, the simplest would be to just use an older version of node-lmdb.

**Comment by Venemo** [comment]
@mux  
Good news: a couple of minimal changes can make it compile on node v0.10.  
Bad news: I'm getting a segfault... :(

**Comment by Venemo** [comment]
Not sure where the segfault comes from, though. The node-lmdb test suite is incompatible with node v0.10, so it could very well be just some problems on the javascript side.

**Comment by Venemo** [comment]
@mux I published a new version on npm which should work on node v0.10, at least I verified that all the examples (excluding the one which uses the newer node `Buffer` API) work. Can you give it a try?

**Comment by Venemo** [comment]
I'm closing this issue now. Please reopen if you have any trouble with this feature.
