### ISSUE TITLE
Fails to compile on Node v8

### ISSUE THREAD

**Issue by pasimako** [Venemo/node-lmdb#127]
node-gyp fails to compile on Ubuntu 17.10 after npm install:

>   CC(target) Release/obj.target/node-lmdb/dependencies/lmdb/libraries/liblmdb/mdb.o
  CC(target) Release/obj.target/node-lmdb/dependencies/lmdb/libraries/liblmdb/midl.o
  CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o
  CXX(target) Release/obj.target/node-lmdb/src/env.o
../src/env.cpp: In lambda function:
../src/env.cpp:332:19: error: could not convert ‘* d->EnvSyncData::callback’ from ‘Nan::Callback’ to ‘v8::Local<v8::Function>’
         Nan::Call(*(d->callback), argc, argv);
                   ^~~~~~~~~~~~~~
node-lmdb.target.mk:121: recipe for target 'Release/obj.target/node-lmdb/src/env.o' failed
make: *** [Release/obj.target/node-lmdb/src/env.o] Error 1

Node: 8.11.1
Npm: 5.6.0

This issue might be related to #123.

**Comment by Venemo** [comment]
This is weird, it does compile for me on node v8. But otherwise the problem is indeed similar to #123

**Comment by Venemo** [comment]
@pasimako Can you still reproduce this with latest master?

**Comment by pasimako** [comment]
@Venemo It compiles without any errors. Thank you! :+1:
