### ISSUE TITLE
Could not build on OS X

### ISSUE THREAD

**Issue by xinli2k5** [Venemo/node-lmdb#48]
`$ node-gyp build`
`gyp info it worked if it ends with ok`
`gyp info using node-gyp@3.3.0`
`gyp info using node@0.10.32 | darwin | x64`
`gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR`
`gyp info spawn make`
`gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]`
`CC(target) Release/obj.target/node-lmdb/libraries/liblmdb/mdb.o`
`../libraries/liblmdb/mdb.c:9671:46: warning: data argument not used by format string [-Wformat-extra-args]`
`(int)mr[i].mr_pid, (size_t)mr[i].mr_tid, txnid);`
`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~`
`/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'`
`__builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)`
`^`
`1 warning generated.`
`CC(target) Release/obj.target/node-lmdb/libraries/liblmdb/midl.o`
`CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o`
`CXX(target) Release/obj.target/node-lmdb/src/env.o`
`../src/env.cpp:199:23: error: no matching constructor for initialization of 'Nan::Callback'`
`d->callback = new Nan::Callback(callback);`
`^             ~~~~~~~~`
`../node_modules/nan/nan.h:1361:12: note: candidate constructor not viable: no known conversion from 'Handle<v8::Function>' to 'const v8::Local<v8::Function>' for 1st argument`
`explicit Callback(const v8::Local<v8::Function> &fn) {`
`^`
`../node_modules/nan/nan.h:1439:33: note: candidate constructor not viable: no known conversion from 'Handle<v8::Function>' to 'const Nan::Callback' for 1st argument`
`NAN_DISALLOW_ASSIGN_COPY_MOVE(Callback)`
`^`
`../node_modules/nan/nan.h:129:23: note: expanded from macro 'NAN_DISALLOW_ASSIGN_COPY_MOVE'`
`NAN_DISALLOW_COPY(CLASS)                                                   \`
`^`
`../node_modules/nan/nan.h:105:35: note: expanded from macro 'NAN_DISALLOW_COPY'`
`# define NAN_DISALLOW_COPY(CLASS) CLASS(const CLASS&) = delete;`
`^`
`../node_modules/nan/nan.h:1439:33: note: candidate constructor not viable: no known conversion from 'Handle<v8::Function>' to 'Nan::Callback' for 1st argument`
`NAN_DISALLOW_ASSIGN_COPY_MOVE(Callback)`
`^`
`../node_modules/nan/nan.h:130:23: note: expanded from macro 'NAN_DISALLOW_ASSIGN_COPY_MOVE'`
`NAN_DISALLOW_MOVE(CLASS)`
`^`
`../node_modules/nan/nan.h:107:5: note: expanded from macro 'NAN_DISALLOW_MOVE'`
`CLASS(CLASS&&) = delete;  /* NOLINT(build/c++11) */                        \`
`^`
`../node_modules/nan/nan.h:1355:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided`
`Callback() {`
`^`
`../src/env.cpp:220:22: error: no matching member function for call to 'Call'`
`d->callback->Call(argc, argv);`
`~~~~~~~~~~~~~^~~~`
`../node_modules/nan/nan.h:1429:3: note: candidate function not viable: no known conversion from 'Handle<v8::Value> [1]' to 'v8::Local<v8::Value> *' for 2nd argument`
`Call(int argc, v8::Local<v8::Value> argv[]) const {`
`^`
`../node_modules/nan/nan.h:1417:3: note: candidate function not viable: requires 3 arguments, but 2 were provided`
`Call(v8::Local<v8::Object> target`
`^`
`2 errors generated.`
`make: *** [Release/obj.target/node-lmdb/src/env.o] Error 1`

**Comment by Venemo** [comment]
Which version of node do you use?

**Comment by xinli2k5** [comment]
`$ node -v`
`v0.10.32`

**Comment by Venemo** [comment]
I haven't tested with 0.10 for a while, but @Matt-Esch did, so maybe #56 will fix this.

**Comment by nikunjy** [comment]
Tried building on OS X and have similar issues 


  CC(target) Release/obj.target/node-lmdb/libraries/liblmdb/mdb.o
../libraries/liblmdb/mdb.c:9671:46: warning: data argument not used by format string [-Wformat-extra-args]
                                (int)mr[i].mr_pid, (size_t)mr[i].mr_tid, txnid);
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
1 warning generated.
  CC(target) Release/obj.target/node-lmdb/libraries/liblmdb/midl.o
  CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o
  CXX(target) Release/obj.target/node-lmdb/src/env.o
../src/env.cpp:200:23: error: no matching constructor for initialization of 'Nan::Callback'
    d->callback = new Nan::Callback(callback);
                      ^             ~~~~~~~~
../node_modules/nan/nan.h:1361:12: note: candidate constructor not viable: no known conversion from 'Handle<v8::Function>' to 'const v8::Local<v8::Function>' for 1st argument
  explicit Callback(const v8::Local<v8::Function> &fn) {
           ^
../node_modules/nan/nan.h:1439:33: note: candidate constructor not viable: no known conversion from 'Handle<v8::Function>' to 'const Nan::Callback' for 1st argument
  NAN_DISALLOW_ASSIGN_COPY_MOVE(Callback)
                                ^
../node_modules/nan/nan.h:129:23: note: expanded from macro 'NAN_DISALLOW_ASSIGN_COPY_MOVE'
    NAN_DISALLOW_COPY(CLASS)                                                   \
                      ^
../node_modules/nan/nan.h:105:35: note: expanded from macro 'NAN_DISALLOW_COPY'
# define NAN_DISALLOW_COPY(CLASS) CLASS(const CLASS&) = delete;
                                  ^
../node_modules/nan/nan.h:1439:33: note: candidate constructor not viable: no known conversion from 'Handle<v8::Function>' to 'Nan::Callback' for 1st argument
  NAN_DISALLOW_ASSIGN_COPY_MOVE(Callback)
                                ^
../node_modules/nan/nan.h:130:23: note: expanded from macro 'NAN_DISALLOW_ASSIGN_COPY_MOVE'
    NAN_DISALLOW_MOVE(CLASS)
                      ^
../node_modules/nan/nan.h:107:5: note: expanded from macro 'NAN_DISALLOW_MOVE'
    CLASS(CLASS&&) = delete;  /* NOLINT(build/c++11) */                        \
    ^
../node_modules/nan/nan.h:1355:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  Callback() {
  ^
../src/env.cpp:221:22: error: no matching member function for call to 'Call'
        d->callback->Call(argc, argv);
        ~~~~~~~~~~~~~^~~~
../node_modules/nan/nan.h:1429:3: note: candidate function not viable: no known conversion from 'Handle<v8::Value> [1]' to 'v8::Local<v8::Value> *' for 2nd argument
  Call(int argc, v8::Local<v8::Value> argv[]) const {
  ^
../node_modules/nan/nan.h:1417:3: note: candidate function not viable: requires 3 arguments, but 2 were provided
  Call(v8::Local<v8::Object> target
  ^
2 errors generated.
make: *** [Release/obj.target/node-lmdb/src/env.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/nikunjyadav/.nvm/v0.10.32/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/Users/nikunjyadav/.nvm/v0.10.32/bin/node-gyp" "build"
gyp ERR! cwd /Users/nikunjyadav/Uber/node-lmdb
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by guymguym** [comment]
Hi, same issue with node 4.4.2(OSX 10.11.4):

```
$ npm install node-lmdb
/
> node-lmdb@0.3.0 install ./node_modules/node-lmdb
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CC(target) Release/obj.target/node-lmdb/libraries/liblmdb/mdb.o
../libraries/liblmdb/mdb.c:8506:46: warning: data argument not used by format string [-Wformat-extra-args]
                                (int)mr[i].mr_pid, (size_t)mr[i].mr_tid, txnid);
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
1 warning generated.
  CC(target) Release/obj.target/node-lmdb/libraries/liblmdb/midl.o
  CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o
In file included from ../src/node-lmdb.cpp:24:
In file included from ../src/node-lmdb.h:30:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../node_modules/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
~/.node-gyp/4.4.2/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for
      3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
~/.node-gyp/4.4.2/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
~/.node-gyp/4.4.2/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
~/.node-gyp/4.4.2/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/node-lmdb.cpp:24:
In file included from ../src/node-lmdb.h:30:
../node_modules/nan/nan.h:772:12: error: no viable conversion from returned value of type 'v8::MaybeLocal<v8::Object>' to function return type 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/.node-gyp/4.4.2/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to
      'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
~/.node-gyp/4.4.2/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object> &&' for 1st argument
~/.node-gyp/4.4.2/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
~/.node-gyp/4.4.2/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/node-lmdb.cpp:24:
In file included from ../src/node-lmdb.h:30:
../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/node-lmdb.cpp:24:
In file included from ../src/node-lmdb.h:27:
~/.node-gyp/4.4.2/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
~/.node-gyp/4.4.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:501:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/node-lmdb.cpp:24:
In file included from ../src/node-lmdb.h:27:
~/.node-gyp/4.4.2/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
~/.node-gyp/4.4.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:511:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/node-lmdb.cpp:24:
In file included from ../src/node-lmdb.h:27:
~/.node-gyp/4.4.2/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
~/.node-gyp/4.4.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1645:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../src/node-lmdb.cpp:24:
In file included from ../src/node-lmdb.h:27:
~/.node-gyp/4.4.2/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
~/.node-gyp/4.4.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1776:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
10 errors generated.
make: *** [Release/obj.target/node-lmdb/src/node-lmdb.o] Error 1
```

**Comment by Venemo** [comment]
@xinli2k5 @guymguym Could you guys try this again with the latest revision?

**Comment by braydonf** [comment]
FYI, tested the build on another machine running OSX 10.9.2 and all tests are working with Node.js v4.4.7.

**Comment by Venemo** [comment]
Thanks @braydonf for taking a look at it. I'll wait a little bit for the other guys to test and then close this ticket. :)

**Comment by Venemo** [comment]
Since there is no more feedback on this issue, I'll take it that the current version works correctly on OS X. Please open another issue if you guys see any problems.
