### ISSUE TITLE
C++11 doesn't compile on Centos GCC 4.4

### ISSUE THREAD

**Issue by matt453** [Venemo/node-lmdb#30]
Cannot get the LMDB to compile.  here are my server details:

We are running:
CentOS 6.5 x86_64
gcc version 4.4.7
node 0.10.28

and here is the failed build log

```
root@dev01-ident node-lmdb]# node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.1
gyp info using node@0.10.28 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/root/node-lmdb/build'
 CC(target) Release/obj.target/node-lmdb/libraries/liblmdb/mdb.o
cc1: warning: command line option "-std=c++0x" is valid for C++/ObjC++ but not for C
cc1: warning: command line option "-fvisibility-inlines-hidden" is valid for C++/ObjC++ but not for C
 CC(target) Release/obj.target/node-lmdb/libraries/liblmdb/midl.o
cc1: warning: command line option "-std=c++0x" is valid for C++/ObjC++ but not for C
cc1: warning: command line option "-fvisibility-inlines-hidden" is valid for C++/ObjC++ but not for C
 CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o
 CXX(target) Release/obj.target/node-lmdb/src/env.o
../src/env.cpp: In constructor â€˜EnvWrap::EnvWrap()â€™:
../src/env.cpp:42: error: â€˜nullptrâ€™ was not declared in this scope
../src/env.cpp: In static member function â€˜static v8::Handle<v8::Value> EnvWrap::open(const v8::Arguments&)â€™:
../src/env.cpp:146: error: â€˜nullptrâ€™ was not declared in this scope
../src/env.cpp: In static member function â€˜static v8::Handle<v8::Value> EnvWrap::close(const v8::Arguments&)â€™:
../src/env.cpp:166: error: â€˜nullptrâ€™ was not declared in this scope
../src/env.cpp: In static member function â€˜static v8::Handle<v8::Value> EnvWrap::sync(const v8::Arguments&)â€™:
../src/env.cpp:209: error: expected primary-expression before â€˜[â€™ token
../src/env.cpp:209: error: expected primary-expression before â€˜]â€™ token
../src/env.cpp:209: error: expected primary-expression before â€˜*â€™ token
../src/env.cpp:209: error: â€˜requestâ€™ was not declared in this scope
../src/env.cpp:209: error: expected unqualified-id before â€˜voidâ€™
../src/env.cpp:213: error: expected primary-expression before â€˜[â€™ token
../src/env.cpp:213: error: expected primary-expression before â€˜]â€™ token
../src/env.cpp:213: error: expected primary-expression before â€˜*â€™ token
../src/env.cpp:213: error: expected primary-expression before â€˜intâ€™
../src/env.cpp:213: error: expected unqualified-id before â€˜voidâ€™
make: *** [Release/obj.target/node-lmdb/src/env.o] Error 1
make: Leaving directory `/root/node-lmdb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 2.6.32-431.17.1.el6.x86_64
gyp ERR! command "node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /root/node-lmdb
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
```

I ran it by my server host technician, and he did not fair any better.
